#!/usr/bin/env bash

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone -b termux https://github.com/btwOreO/jarvis
    cd Jarvis
fi
bash resources/startup/termux.sh
